name: matrix
on: push
jobs:
  build:
    strategy:
      #fail-fast: 
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: dependencies
        run: npm ci
      - name: build
        run: npm run build